"""Add address column

Revision ID: 032be07caf9b
Revises: 3b0db4663464
Create Date: 2025-08-15 15:32:42.380505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032be07caf9b'
down_revision: Union[str, Sequence[str], None] = '3b0db4663464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_profile_pic_url'), 'users', ['profile_pic_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_profile_pic_url'), table_name='users')
    op.drop_column('users', 'profile_pic_url')
    # ### end Alembic commands ###
