"""Add address column

Revision ID: cb4e346ad21c
Revises: 032be07caf9b
Create Date: 2025-08-16 12:54:49.344743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4e346ad21c'
down_revision: Union[str, Sequence[str], None] = '032be07caf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_resource_text'), table_name='resources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resources_resource_text'), 'resources', ['resource_text'], unique=False)
    # ### end Alembic commands ###
